[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=%(ENV_SUPERVISORD_PID_PATH)s
childlogdir=/var/log/supervisor
logfile_maxbytes=5MB
logfile_backups=2
loglevel=info
silent=true

[unix_http_server]
file=%(ENV_SUPERVISORD_SOCKET_PATH)s
username=%(ENV_SUPERVISORD_USER)s
password=%(ENV_SUPERVISORD_PASSWORD)s

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix://%(ENV_SUPERVISORD_SOCKET_PATH)s

[program:xray]
command=/usr/local/bin/rw-core run -config %(ENV_XRAY_CONFIG_PATH)s
autostart=false
autorestart=false
stderr_logfile=/var/log/supervisor/xray.err.log
stdout_logfile=/var/log/supervisor/xray.out.log
stdout_logfile_maxbytes=5MB
stderr_logfile_maxbytes=5MB
stdout_logfile_backups=0
stderr_logfile_backups=0

[program:sing-box]
command=/usr/local/bin/sing-box run -c %(ENV_SING_BOX_CONFIG_PATH)s
autostart=false
autorestart=false
stderr_logfile=/var/log/supervisor/sing-box.err.log
stdout_logfile=/var/log/supervisor/sing-box.out.log
stdout_logfile_maxbytes=5MB
stderr_logfile_maxbytes=5MB
stdout_logfile_backups=0
stderr_logfile_backups=0
